"""Build the deterministic static miniGPT Public Playground site."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING, Never, cast
from urllib.parse import urlsplit

if TYPE_CHECKING:
    from collections.abc import Sequence

_CONFIG_SLOT = "__DEMO_API_BASE_JSON__"
_SITE_FILES = ("index.html", "styles.css", "app.js")
_MARKER_NAME = ".minigpt-public-demo-site"
_MARKER_CONTENT = "generated by scripts/build_public_demo_site.py\n"


def normalize_api_base(value: str) -> str:
    """Accept an empty offline build or one credential-free HTTPS origin."""
    if value == "":
        return ""
    if value != value.strip():
        _invalid("DEMO_API_BASE must not contain surrounding whitespace")
    try:
        parsed = urlsplit(value)
        port = parsed.port
    except ValueError as error:
        _invalid(f"DEMO_API_BASE is invalid: {error}")
    if parsed.scheme != "https":
        _invalid("DEMO_API_BASE must be empty or use https")
    if parsed.hostname is None:
        _invalid("DEMO_API_BASE must contain a hostname")
    if parsed.username is not None or parsed.password is not None:
        _invalid("DEMO_API_BASE must not contain credentials")
    if parsed.path not in {"", "/"} or parsed.query or parsed.fragment:
        _invalid("DEMO_API_BASE must be an origin without path, query, or fragment")
    host = parsed.hostname.lower()
    if ":" in host:
        host = f"[{host}]"
    port_suffix = "" if port in {None, 443} else f":{port}"
    return f"https://{host}{port_suffix}"


def build_site(*, source: Path, output: Path, api_base: str) -> None:  # noqa: C901
    """Copy audited assets and atomically publish one generated config.js."""
    normalized_base = normalize_api_base(api_base)
    source = source.resolve()
    output = output.resolve()
    if not source.is_dir():
        _invalid(f"web source directory does not exist: {source}")
    if output == source or output in source.parents or source in output.parents:
        _invalid("output directory must not contain or equal the web source")
    if output.exists() and not (output / _MARKER_NAME).is_file():
        _invalid(f"refusing to replace an unmanaged output directory: {output}")
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = Path(tempfile.mkdtemp(prefix=f".{output.name}-", dir=output.parent)).resolve()
    backup = output.with_name(f".{output.name}-previous")
    try:
        for name in _SITE_FILES:
            _copy_regular_file(source / name, temporary / name)
        _copy_directory(source / "assets", temporary / "assets", label="web/assets")
        _copy_directory(source / "data", temporary / "data", label="web/data")
        template_path = source / "config.template.js"
        template = template_path.read_text(encoding="utf-8")
        if template.count(_CONFIG_SLOT) != 1:
            _invalid("config.template.js must contain exactly one API Base token")
        rendered = template.replace(
            _CONFIG_SLOT,
            json.dumps(normalized_base, ensure_ascii=True),
        )
        _atomic_write(temporary / "config.js", rendered)
        _atomic_write(temporary / ".nojekyll", "")
        _atomic_write(temporary / _MARKER_NAME, _MARKER_CONTENT)
        if backup.exists():
            _invalid(f"stale site backup blocks a safe build: {backup}")
        if output.exists():
            _ = output.replace(backup)
        try:
            _ = temporary.replace(output)
        except OSError:
            if backup.exists() and not output.exists():
                _ = backup.replace(output)
            raise
        if backup.exists():
            shutil.rmtree(backup)
    finally:
        if temporary.exists():
            shutil.rmtree(temporary)


def _copy_regular_file(source: Path, destination: Path) -> None:
    if not source.is_file() or source.is_symlink():
        _invalid(f"required web asset must be a regular file: {source}")
    destination.parent.mkdir(parents=True, exist_ok=True)
    _ = shutil.copyfile(source, destination)


def _copy_directory(source: Path, destination: Path, *, label: str) -> None:
    """Copy one optional audited asset tree without following symlinks."""
    if not source.exists():
        return
    if not source.is_dir() or source.is_symlink():
        _invalid(f"{label} must be an ordinary directory")
    for item in sorted(source.rglob("*")):
        if item.is_symlink():
            _invalid(f"{label} must not contain symlinks: {item}")
        if item.is_dir():
            continue
        if not item.is_file():
            _invalid(f"{label} must contain only regular files: {item}")
        relative = item.relative_to(source)
        _copy_regular_file(item, destination / relative)


def _atomic_write(path: Path, content: str) -> None:
    temporary = path.with_name(f".{path.name}.tmp")
    _ = temporary.write_text(content, encoding="utf-8", newline="\n")
    _ = temporary.replace(path)


def _invalid(reason: str) -> Never:
    raise ValueError(reason)


def build_parser() -> argparse.ArgumentParser:
    """Create the static-site build parser."""
    parser = argparse.ArgumentParser(description=__doc__)
    _ = parser.add_argument("--source", type=Path, default=Path("web"))
    _ = parser.add_argument("--output", type=Path, default=Path("_site"))
    _ = parser.add_argument("--api-base")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Build from CLI arguments and the non-secret DEMO_API_BASE variable."""
    arguments = build_parser().parse_args(argv)
    values = cast("dict[str, object]", vars(arguments))
    explicit_base = cast("str | None", values["api_base"])
    build_site(
        source=cast("Path", values["source"]),
        output=cast("Path", values["output"]),
        api_base=os.environ.get("DEMO_API_BASE", "") if explicit_base is None else explicit_base,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
