"use strict";

(() => {
  const HEALTH_INTERVAL_MS = 60_000;
  const HEALTH_TIMEOUT_MS = 6_000;
  const STATIC_EXAMPLE = "ROMEO:\nBut soft, what light through yonder window breaks?";
  const REQUEST_HEADERS = Object.freeze({ "ngrok-skip-browser-warning": "1" });
  const configuration = window.MINIGPT_DEMO_CONFIG ?? Object.freeze({ apiBase: "" });
  const apiBase = typeof configuration.apiBase === "string" ? configuration.apiBase : "";

  const elements = Object.freeze({
    form: document.querySelector("#completion-form"),
    prompt: document.querySelector("#prompt"),
    maxTokens: document.querySelector("#max-tokens"),
    temperature: document.querySelector("#temperature"),
    seed: document.querySelector("#seed"),
    stream: document.querySelector("#stream"),
    generate: document.querySelector("#generate"),
    stop: document.querySelector("#stop"),
    clear: document.querySelector("#clear"),
    requestStatus: document.querySelector("#request-status"),
    backendChip: document.querySelector("#backend-chip"),
    backendState: document.querySelector("#backend-state"),
    output: document.querySelector("#output"),
    outputMode: document.querySelector("#output-mode"),
    outputNote: document.querySelector("#output-note"),
    metricStatus: document.querySelector("#metric-status"),
    metricTtft: document.querySelector("#metric-ttft"),
    metricElapsed: document.querySelector("#metric-elapsed"),
    metricTokens: document.querySelector("#metric-tokens"),
    metricRate: document.querySelector("#metric-rate"),
    metricExecutor: document.querySelector("#metric-executor"),
    metricKv: document.querySelector("#metric-kv"),
    metricQueue: document.querySelector("#metric-queue"),
  });

  const state = {
    online: false,
    activeController: null,
    healthTimer: null,
    lastHealthCheckAt: 0,
    stopRequested: false,
    requestStartedAt: 0,
    firstTokenAt: null,
    generatedTokens: 0,
    elapsedTimer: null,
    modelId: "minigpt-char",
  };

  function apiUrl(path) {
    return new URL(path, `${apiBase}/`).toString();
  }

  function apiFetch(path, options = {}) {
    const suppliedHeaders = options.headers ?? {};
    return fetch(apiUrl(path), {
      ...options,
      cache: "no-store",
      credentials: "omit",
      referrerPolicy: "no-referrer",
      headers: { ...REQUEST_HEADERS, ...suppliedHeaders },
    });
  }

  function setBackendOnline(online, label) {
    state.online = online;
    elements.backendChip.classList.toggle("online", online);
    elements.backendChip.classList.toggle("offline", !online);
    elements.backendState.textContent = label;
    elements.generate.disabled = !online || state.activeController !== null;
    if (!online && state.activeController === null && elements.output.textContent.trim() === "") {
      showStaticExample();
    }
  }

  function showStaticExample() {
    elements.output.textContent = STATIC_EXAMPLE;
    elements.outputMode.textContent = "Static example";
    elements.outputNote.textContent =
      "Static example shown while the local Windows backend is offline.";
  }

  function setRequestStatus(message, isError = false) {
    elements.requestStatus.textContent = message;
    elements.requestStatus.classList.toggle("error", isError);
  }

  function formatDuration(milliseconds) {
    if (!Number.isFinite(milliseconds) || milliseconds < 0) {
      return "—";
    }
    if (milliseconds < 1000) {
      return `${Math.round(milliseconds)} ms`;
    }
    return `${(milliseconds / 1000).toFixed(2)} s`;
  }

  function updateRequestMetrics() {
    if (state.requestStartedAt === 0) {
      return;
    }
    const elapsedMilliseconds = performance.now() - state.requestStartedAt;
    elements.metricElapsed.textContent = formatDuration(elapsedMilliseconds);
    elements.metricTokens.textContent = `${state.generatedTokens} tokens`;
    elements.metricRate.textContent =
      state.generatedTokens === 0 || elapsedMilliseconds <= 0
        ? "—"
        : `${((state.generatedTokens * 1000) / elapsedMilliseconds).toFixed(2)} tok/s`;
    elements.metricTtft.textContent =
      state.firstTokenAt === null
        ? "—"
        : formatDuration(state.firstTokenAt - state.requestStartedAt);
  }

  function beginRequest(prompt) {
    state.stopRequested = false;
    state.requestStartedAt = performance.now();
    state.firstTokenAt = null;
    state.generatedTokens = 0;
    elements.output.textContent = prompt;
    elements.outputMode.textContent = "Live model";
    elements.outputNote.textContent = "Generated by the local CPU model through the public tunnel.";
    elements.metricStatus.textContent = "Submitting";
    elements.metricTtft.textContent = "—";
    elements.metricElapsed.textContent = "0 ms";
    elements.metricTokens.textContent = "0 tokens";
    elements.metricRate.textContent = "—";
    elements.generate.disabled = true;
    elements.stop.disabled = false;
    elements.clear.disabled = true;
    setRequestStatus("Submitting one bounded completion request…");
    state.elapsedTimer = window.setInterval(updateRequestMetrics, 100);
  }

  function endRequest() {
    if (state.elapsedTimer !== null) {
      window.clearInterval(state.elapsedTimer);
      state.elapsedTimer = null;
    }
    updateRequestMetrics();
    elements.stop.disabled = true;
    elements.clear.disabled = false;
    elements.generate.disabled = !state.online;
    state.activeController = null;
  }

  function appendModelText(text) {
    if (text.length === 0) {
      return;
    }
    if (state.firstTokenAt === null) {
      state.firstTokenAt = performance.now();
    }
    elements.output.textContent = `${elements.output.textContent}${text}`;
    state.generatedTokens += 1;
    elements.metricStatus.textContent = "Streaming";
    updateRequestMetrics();
  }

  function serverErrorMessage(documentValue, fallback) {
    if (
      documentValue !== null &&
      typeof documentValue === "object" &&
      documentValue.error !== null &&
      typeof documentValue.error === "object" &&
      typeof documentValue.error.message === "string"
    ) {
      return documentValue.error.message;
    }
    return fallback;
  }

  async function responseError(response) {
    let documentValue = null;
    try {
      documentValue = await response.json();
    } catch {
      return `Backend request failed with HTTP ${response.status}.`;
    }
    return serverErrorMessage(documentValue, `Backend request failed with HTTP ${response.status}.`);
  }

  function readChoiceText(documentValue) {
    if (
      documentValue === null ||
      typeof documentValue !== "object" ||
      !Array.isArray(documentValue.choices) ||
      documentValue.choices.length === 0 ||
      documentValue.choices[0] === null ||
      typeof documentValue.choices[0] !== "object" ||
      typeof documentValue.choices[0].text !== "string"
    ) {
      throw new Error("Backend returned an invalid completion envelope.");
    }
    return documentValue.choices[0].text;
  }

  function updateUsage(documentValue) {
    if (
      documentValue !== null &&
      typeof documentValue === "object" &&
      documentValue.usage !== null &&
      typeof documentValue.usage === "object" &&
      Number.isInteger(documentValue.usage.completion_tokens)
    ) {
      state.generatedTokens = documentValue.usage.completion_tokens;
    }
  }

  function consumeSseData(data) {
    if (data === "[DONE]") {
      return true;
    }
    let documentValue;
    try {
      documentValue = JSON.parse(data);
    } catch {
      throw new Error("Backend returned malformed streaming data.");
    }
    if (
      documentValue !== null &&
      typeof documentValue === "object" &&
      documentValue.error !== null &&
      typeof documentValue.error === "object"
    ) {
      throw new Error(serverErrorMessage(documentValue, "Streaming generation failed."));
    }
    appendModelText(readChoiceText(documentValue));
    updateUsage(documentValue);
    return false;
  }

  async function readSse(response) {
    if (response.body === null) {
      throw new Error("Streaming is unavailable in this browser.");
    }
    const reader = response.body.getReader();
    const decoder = new TextDecoder("utf-8", { fatal: true });
    let buffer = "";
    let finished = false;
    while (!finished) {
      const { value, done } = await reader.read();
      buffer += decoder.decode(value ?? new Uint8Array(), { stream: !done });
      const lines = buffer.split(/\r?\n/);
      buffer = lines.pop() ?? "";
      for (const line of lines) {
        if (!line.startsWith("data:")) {
          continue;
        }
        finished = consumeSseData(line.slice(5).trimStart());
        if (finished) {
          break;
        }
      }
      if (done) {
        break;
      }
    }
    if (!finished) {
      throw new Error("Streaming ended before the completion sentinel.");
    }
  }

  async function readNonStream(response) {
    const documentValue = await response.json();
    const text = readChoiceText(documentValue);
    if (text.length > 0 && state.firstTokenAt === null) {
      state.firstTokenAt = performance.now();
    }
    elements.output.textContent = `${elements.output.textContent}${text}`;
    updateUsage(documentValue);
    updateRequestMetrics();
  }

  async function refreshMetrics() {
    if (!state.online || apiBase === "") {
      return;
    }
    try {
      const response = await apiFetch("demo/metrics");
      if (!response.ok) {
        return;
      }
      const metrics = await response.json();
      if (Number.isInteger(metrics.queued_requests)) {
        elements.metricQueue.textContent = String(metrics.queued_requests);
      }
    } catch {
      elements.metricQueue.textContent = "—";
    }
  }

  async function submitCompletion(event) {
    event.preventDefault();
    if (!state.online || state.activeController !== null) {
      return;
    }
    if (!elements.form.reportValidity()) {
      return;
    }
    const prompt = elements.prompt.value;
    if (prompt.trim().length === 0) {
      setRequestStatus("Enter a prompt before generating.", true);
      elements.prompt.focus();
      return;
    }
    const payload = {
      model: state.modelId,
      prompt,
      max_tokens: Number(elements.maxTokens.value),
      temperature: Number(elements.temperature.value),
      seed: Number(elements.seed.value),
      stream: elements.stream.checked,
    };
    const controller = new AbortController();
    state.activeController = controller;
    beginRequest(prompt);

    try {
      const response = await apiFetch("v1/completions", {
        method: "POST",
        signal: controller.signal,
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      if (!response.ok) {
        throw new Error(await responseError(response));
      }
      if (payload.stream) {
        await readSse(response);
      } else {
        await readNonStream(response);
      }
      elements.metricStatus.textContent = "Complete";
      setRequestStatus("Generation complete.");
      await refreshMetrics();
    } catch (error) {
      if (error instanceof DOMException && error.name === "AbortError") {
        elements.metricStatus.textContent = "Stopped";
        setRequestStatus(
          state.stopRequested ? "Generation stopped by user." : "Generation request was cancelled.",
          !state.stopRequested,
        );
      } else {
        const message = error instanceof Error ? error.message : "Generation failed.";
        elements.metricStatus.textContent = "Failed";
        setRequestStatus(message, true);
        if (error instanceof TypeError) {
          setBackendOnline(false, "Backend offline");
        }
      }
    } finally {
      endRequest();
    }
  }

  function applyInfo(info) {
    if (typeof info.model_id === "string") {
      state.modelId = info.model_id;
    }
    if (typeof info.executor === "string") {
      elements.metricExecutor.textContent = info.executor;
    }
    if (typeof info.kv_cache_backend === "string") {
      elements.metricKv.textContent = info.kv_cache_backend;
    }
    if (info.limits !== null && typeof info.limits === "object") {
      if (Number.isInteger(info.limits.max_prompt_characters)) {
        elements.prompt.maxLength = info.limits.max_prompt_characters;
      }
      if (Number.isInteger(info.limits.max_new_tokens)) {
        elements.maxTokens.max = String(info.limits.max_new_tokens);
      }
      if (Number.isFinite(info.limits.min_temperature)) {
        elements.temperature.min = String(info.limits.min_temperature);
      }
      if (Number.isFinite(info.limits.max_temperature)) {
        elements.temperature.max = String(info.limits.max_temperature);
      }
    }
  }

  function scheduleHealthCheck() {
    if (apiBase === "" || document.hidden) {
      return;
    }
    if (state.healthTimer !== null) {
      window.clearTimeout(state.healthTimer);
    }
    const elapsed = Date.now() - state.lastHealthCheckAt;
    const delay = Math.max(0, HEALTH_INTERVAL_MS - elapsed);
    state.healthTimer = window.setTimeout(checkHealth, delay);
  }

  async function checkHealth() {
    state.healthTimer = null;
    if (apiBase === "" || document.hidden) {
      return;
    }
    state.lastHealthCheckAt = Date.now();
    const controller = new AbortController();
    const timeout = window.setTimeout(() => controller.abort(), HEALTH_TIMEOUT_MS);
    try {
      const health = await apiFetch("healthz", { signal: controller.signal });
      if (!health.ok) {
        throw new Error("Backend health check failed.");
      }
      const [infoResponse, metricsResponse] = await Promise.all([
        apiFetch("demo/info", { signal: controller.signal }),
        apiFetch("demo/metrics", { signal: controller.signal }),
      ]);
      if (!infoResponse.ok || !metricsResponse.ok) {
        throw new Error("Backend metadata is unavailable.");
      }
      const [info, metrics] = await Promise.all([infoResponse.json(), metricsResponse.json()]);
      applyInfo(info);
      if (Number.isInteger(metrics.queued_requests)) {
        elements.metricQueue.textContent = String(metrics.queued_requests);
      }
      setBackendOnline(true, "Backend online");
      setRequestStatus("Local CPU backend is ready.");
    } catch {
      setBackendOnline(false, "Backend offline");
      elements.metricQueue.textContent = "—";
      setRequestStatus(
        "The local model is offline. Project details and the static example remain available.",
      );
    } finally {
      window.clearTimeout(timeout);
      scheduleHealthCheck();
    }
  }

  function clearPlayground() {
    elements.form.reset();
    elements.prompt.value = "";
    state.requestStartedAt = 0;
    state.firstTokenAt = null;
    state.generatedTokens = 0;
    elements.metricStatus.textContent = "Idle";
    elements.metricTtft.textContent = "—";
    elements.metricElapsed.textContent = "—";
    elements.metricTokens.textContent = "0 tokens";
    elements.metricRate.textContent = "—";
    if (state.online) {
      elements.output.textContent = "";
      elements.outputMode.textContent = "Ready";
      elements.outputNote.textContent = "Choose a preset or enter a character-level prompt.";
      setRequestStatus("Local CPU backend is ready.");
    } else {
      showStaticExample();
    }
    elements.prompt.focus();
  }

  document.querySelectorAll("[data-prompt]").forEach((button) => {
    button.addEventListener("click", () => {
      elements.prompt.value = button.dataset.prompt ?? "";
      elements.prompt.focus();
    });
  });
  elements.form.addEventListener("submit", submitCompletion);
  elements.stop.addEventListener("click", () => {
    state.stopRequested = true;
    state.activeController?.abort();
  });
  elements.clear.addEventListener("click", clearPlayground);
  document.addEventListener("visibilitychange", () => {
    if (document.hidden) {
      if (state.healthTimer !== null) {
        window.clearTimeout(state.healthTimer);
        state.healthTimer = null;
      }
      return;
    }
    scheduleHealthCheck();
  });

  if (apiBase === "") {
    setBackendOnline(false, "Offline-only build");
    setRequestStatus(
      "No backend URL is configured. This static portfolio remains fully available.",
    );
    showStaticExample();
  } else {
    state.lastHealthCheckAt = Date.now() - HEALTH_INTERVAL_MS;
    scheduleHealthCheck();
  }
})();
